### ISSUE TITLE
关于称呼问题

### ISSUE THREAD

**Issue by ChrAlpha** [idealclover/Telegram-Channel-Mirror#2]
那个……其实我叫「Chris」，虽然网络上更愿意被称为「ChrAlpha」，但是直接放个「Chr」连我都很懵的说 😂

望 README 中能更改称呼，感谢！

**Comment by ChrAlpha** [comment]
大概是我的 portfolio 页面描述不清晰，有点误导，给您带来不便还请谅解。

**Comment by idealclover** [comment]
改了哦！称呼写错了好抱歉 XD
